/*********************************************************************************

** The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 * German translation provided by crm-now, www.crm-now.de
 ********************************************************************************/

	
	var alert_arr = {       DELETE:'Sind Sie sicher, dass Sie das tun wollen? ',
                                RECORDS:' Aufzeichnung(en)?',
                                SELECT:'Bitte wenigstens einen Eintrag markieren.',
                                DELETE_ACCOUNT:'Wenn Sie diese Organisation(en) löschen, werden auch die sich darauf beziehenden Potentiale, Angebote, Verkaufsbestellungen und Rechnungen entfernt. Sind Sie sicher, dass Sie das wirklich tun wollen? ',
                                DELETE_VENDOR:'Wenn Sie Lieferanten löschen, werden auch die sich darauf beziehenden Einkaufsbestellungen aus dem CRM entfernt. Sind Sie sicher, dass Sie das wirklich tun wollen?',
                                SELECT_MAILID:'Bitte eine E-Mail Adresse angeben.',
                                OVERWRITE_EXISTING_ACCOUNT2:') ersetzt.',
                                MISSING_FIELDS:'Die Angaben in folgenden Pflichtfelder fehlen:',
                                NOT_ALLOWED_TO_EDIT:'Sie haben keine Berechtigung zum Bearbeiten dieses Feldes',
                                NOT_ALLOWED_TO_EDIT_FIELDS:'ie haben keine Berechtigung zum Bearbeiten',
                                COLUMNS_CANNOT_BE_EMPTY:'Die Spalten dürfen nicht leer sein',
                                CANNOT_BE_EMPTY:' darf nicht leer sein',
                                CANNOT_BE_NONE:' darf nicht leer sein',
                                ENTER_VALID:'Bitte einen gültigen Wert eingeben für ',
                                SHOULDBE_LESS:' muss weniger sein als ',
                                SHOULDBE_LESS_EQUAL:' muss weniger oder gleich ',
                                SHOULDBE_EQUAL:' muss gleich sein zu ',
                                SHOULDBE_GREATER:' muss gößer sein als ',
                                SHOULDBE_GREATER_EQUAL:' muss größer oder gleich ',
                                INVALID:'Ungültig(e) ',
                                EXCEEDS_MAX:' Überschreitet die maximale Grenze ',
                                OUT_OF_RANGE:' ist ausserhalb des zulässigen Bereiches',
                                SHOULDNOTBE_EQUAL:' darf nicht gleich sein zu ',
                                PORTAL_PROVIDE_EMAILID:'Portalnutzer benötigen eine E-Mail Adresse',
                                ADD_CONFIRMATION:'Sind Sie sicher, dass Sie das hinzufügen wollen: ',
                                ACCOUNTNAME_CANNOT_EMPTY:'Der Organisationsname darf nicht leer sein.',
                                CANT_SELECT_CONTACTS:"Aus Leads können keine bezogenen Kontakte ausgewählt werden",
                                LBL_THIS:'Der Eintrag ',
                                DOESNOT_HAVE_MAILIDS:" hat keine E-Mail Adresse.",
                                ARE_YOU_SURE:'Sind Sie sicher?',
                                DOESNOT_HAVE_AN_MAILID:'" '+"hat keine E-Mail Adresse.",
                                MISSING_REQUIRED_FIELDS:'Die Angaben in folgenden Pflichtfelder fehlen: ',
                                READONLY:"nur Lesen",
								SELECT_ATLEAST_ONE_USER:'Btte wenigstens einen Benutzer auswählen',
                                DISABLE_SHARING_CONFIRMATION:'Sind Sie sicher? Sie schränken die Zugriffsrechte ein für  ',
                                USERS:' Nutzer ?',
                                ENDTIME_GREATER_THAN_STARTTIME:'Die Endezeit muss später sein als die Startzeit. ',
                                FOLLOWUPTIME_GREATER_THAN_STARTTIME:'Ein Nachfassen kann nur nach der Startzeit stattfinden. ',
                                MISSING_EVENT_NAME:'Der Name für das Ereignis fehlt',
                                EVENT_TYPE_NOT_SELECTED:'Der Typ des Ereignisses ist nicht definiert',
                                CLOSEDATE_CANNOT_BE_EMPTY:'Sie müssen das Datum angeben.',
                                SITEURL_CANNOT_BE_EMPTY:'Sie müssen eine URL angeben.',
                                SITENAME_CANNOT_BE_EMPTY:'Sie müssen der Seite einen kurzen aber prägnanten Namen geben.',
                                LISTPRICE_CANNOT_BE_EMPTY:'Der Listenpreis darf nicht leer bleiben.',
                                INVALID_LIST_PRICE:'Die Angabe zum Listenpreis ist ungültig.',
                                PROBLEM_ACCESSSING_URL:'Die folgende URL kann nicht erreicht werden: ',
                                CODE:' Code: ',
                                WISH_TO_QUALIFY_MAIL_AS_CONTACT:'Sind Sie sicher, dass Sie diese Mailadresse als Person qualifizieren wollen?',
                                SELECT_ATLEAST_ONEMSG_TO_DEL:'Sie müssen wenigstens eine Nachricht zum Löschen markieren.',
                                ERROR:'Fehler',
                                FIELD_TYPE_NOT_SELECTED:'Die Feldtypen wurden nicht festgelegt.',
                                SPECIAL_CHARACTERS_NOT_ALLOWED:'In dem Label Feld sind keine Sonderzeichen zulässig.',
								SPECIAL_CHARACTERS:'Sonderzeichen',
                                NOT_ALLOWED:'sind nicht zulässig. Bitte benutzen Sie andere Zeichen.',
                                PICKLIST_CANNOT_BE_EMPTY:'Sie müssen in dieser Liste Werte eintragen.',
                                DUPLICATE_VALUES_FOUND:'Doppelte Einträge gefunden',
                                DUPLICATE_MAPPING_ACCOUNTS:'Doppelte Einträge für Organsisationen gefunden!',
                                DUPLICATE_MAPPING_CONTACTS:'Doppelte Einträge für Personen gefunden!',
                                DUPLICATE_MAPPING_POTENTIAL:'Doppelte Einträge für Verkaufspotentiale gefunden!',
                                ERROR_WHILE_EDITING:'Fehler beim Bearbeiten',
                                CURRENCY_CHANGE_INFO:'Der Wechsel der Währung war erfolgreich.',
                                CURRENCY_CONVERSION_INFO:'Nutzen Sie $ als Währung? \n Klicken Sie OK um $ beizubehalten, klicken Sie auf ABBRECHEN um die Währungsumrechnung einzustellen.',
                                THE_EMAILID: "Die E-Mail Adresse \'",
                                EMAIL_FIELD_INVALID:"\' im E-Mail Feld ist ungültig",
                                MISSING_REPORT_NAME:'Sie müssen dem Bericht einen Namen geben.',
                                REPORT_NAME_EXISTS:'Diesen Namen für einen Bericht geibt es bereits, bitte einen anderen Namen angeben.',
                                WANT_TO_CHANGE_CONTACT_ADDR:'Wollen Sie die Adresse der Personen, die zu dieser Organisation gehören auch ändern?',
                                SURE_TO_DELETE:'Sind Sie sicher, dass Sie das wirklich löschen wollen?',
								NO_PRODUCT_SELECTED:'Sie haben kein Produkt ausgewählt. Bitte markieren Sie wenigstens ein Produkt.',
                                VALID_FINAL_PERCENT:'Bitte geben Sie einen gültigen Prozentwert für den Discount an.',
                                VALID_FINAL_AMOUNT:'Bitte geben Sie einen gültigen Prozentwert für den Discount an.',
                                VALID_SHIPPING_CHARGE:'Bitte geben Sie einen gültigen Wert für die Versandkosten an.',
                                VALID_ADJUSTMENT:'Bitte geben Sie einen gültigen Wert für die Anpassung ein.',
                                WANT_TO_CONTINUE:'Weiter?',
                                ENTER_VALID_TAX:'Bitte geben Sie für die Steuer einen gültigen Zahlenwert in Prozent an.',
                                VALID_TAX_NAME:'Bitte geben Sie der Steuer einen gültigen Namen.',
                                CORRECT_TAX_VALUE:'Bitte geben Sie für die Steuer einen gültigen Zahlenwert in Prozent an.',
                                ENTER_POSITIVE_VALUE:'Bitte nur positive Werte benutzen.',
                                LABEL_SHOULDNOT_EMPTY:'Sie müssen der Steuer einen Namen geben.',
                                NOT_VALID_ENTRY:'ist kein güliger Wert. Bitte machen Sie korrekte Angaben.',
                                VALID_DISCOUNT_PERCENT:'Bitte geben Sie für den Discount einen gültigen Zahlenwert in Prozent an.',
                                VALID_DISCOUNT_AMOUNT:'Bitte geben Sie für den Discount einen gültigen Betrag an.',
                                SELECT_TEMPLATE_TO_MERGE:'Bitte wühlen Sie für das Zusammenführen eine Textvorlage aus.',
								SELECTED_MORE_THAN_ONCE:'Sie haben Produkte mehr als einmal ausgewählt.',
								YES:'ja',
                                NO:'nein',
                                MAIL:'E-Mail',
								EQUALS:'gleich zu',
								NOT_EQUALS_TO:'ungleich zu',
								STARTS_WITH:'beginnt mit',
								CONTAINS:'beinhaltet',
								DOES_NOT_CONTAINS:'beinhaltet nicht',
								LESS_THAN:'weniger als',
								GREATER_THAN:'grösser als',
								LESS_OR_EQUALS:'weniger oder gleich',
								GREATER_OR_EQUALS:'grösser oder gleich',
								
								NO_SPECIAL_CHARS:'In diesem Eingabefeld sind nur Buchstaben und Zahlen zulässig.',
								PLS_SELECT_VALID_FILE:'Bitte wählen Sie eine Datei mit einem der folgenden Formate:\n',
									NO_SPECIAL:'Nur Buchstaben und Zahlen zulässig',
								NO_QUOTES:'Angebote (\' ") und + Zeichen sind nicht erlaubt ',
								IN_PROFILENAME:' im Profilnamen',
								IN_GROUPNAME:' im Gruppennamen',
								IN_ROLENAME:' im Rollennamen',
                                VALID_TAX_PERCENT:'Die Angabe für die Steuer ist nicht korrekt',
                                VALID_SH_TAX:'Die Angabe für die Steuer ist nicht korrekt ',
								ROLE_DRAG_ERR_MSG:'Sie können keine übergeordnete Rolle unter eine untergeordnete Rolle verschieben.',
								LBL_DEL:'lö',
								VALID_DATA :' Die Daten sind ungültig. ',
									STDFILTER : 'Standardfilter',
									STARTDATE : 'Startdatum',
									ENDDATE : 'Enddatum',
									START_DATE_TIME : 'Startdatum & -zeit',
									START_TIME : 'Startzeit',
									DATE_SHOULDNOT_PAST :'dem jetzigen Datum und der gegenwärtigen Zeit für geplante Aktivitäten sein.',
									TIME_SHOULDNOT_PAST :'der gegenwärtigen Zeit sein.',
									LBL_AND : 'UND',
								LBL_ENTER_VALID_PORT: 'Bitte geben Sie die Portnummer korrekt an.',
								IN_USERNAME :' im Benutzernamen ',
				LBL_ENTER_VALID_NO: 'Bitte eine richtige Zahl angeben',
				LBL_PROVIDE_YES_NO: ' Falscher Wert.\n Hier gibt es nur Ja oder Nein',
				LBL_SELECT_CRITERIA: ' Falsches Kriterium.\n Bitte ein gültiges Kriterium wählen.',
				// Added/Updated for vtiger CRM 5.0.4
								OPPORTUNITYNAME_CANNOT_BE_EMPTY:'Das Feld für den Potentialnamen muß ausgefüllt werden.',
				                		OVERWRITE_EXISTING_ACCOUNT1:'Wollen Sie die existierende Adresse durch die Adresse der ausgewählten Organisation ersetzen?',
										NAME_DESC:' für Verzeichnisname & Beschreibung',
						                		ENDS_WITH:'endet mit',
						                		SHARED_EVENT_DEL_MSG:'Sie haben keine Berechtigung zum Ändern & Löschen von dieser Aktivität.',
                                                                                                                             

				LBL_WRONG_IMAGE_TYPE: 'Folgende Dateitypen sind zulässig: jpeg, png, jpg, pjpeg, x-png oder gif',
				SELECT_MAIL_MOVE: 'Bitte markieren Sie zuerst eine E-Mail.',
				
				LBL_NOTSEARCH_WITHSEARCH_ALL:'Sie haben keine spezielle Auswahl getroffen. Alle vorhandenen Daten werden exportiert aus: ',
				LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE:'Sie haben keine spezielle Auswahl mit der Suchfunktion getroffen, aber wollen die Ergebnisse einer Suche und der aktuellen Seite berücksichtigen. Folglich kann nur die aktuelle Seite exportiert werden aus: ',
				LBL_NO_DATA_SELECTED:'Sie haben keine Auswahl getroffen. Für einen Export muessen Sie wenigstens einen Eintrag auswählen.',
				LBL_SEARCH_WITHOUTSEARCH_ALL:'Sie haben die Suchfunktion verwendet, um Daten auszuwählen. Jedoch haben Sie ihr Exportkriterium darauf nicht bezogen. Wenn Sie auf [ok] klicken werden alle Daten exportiert. Wenn Sie auf [Abbrechen] klicken, können Sie Ihre Exportkriterien neu bestimmen.',
				STOCK_IS_NOT_ENOUGH : 'Ihr Lager hat so viel nicht vorrätig.',
				INVALID_QTY : 'ungültige Mengenangabe',
				LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE:'Sie haben die Suchfunktion verwendet, um Daten auszuwählen. Jedoch haben Sie ihr Exportkriterium daruaf nicht bezogen. Wenn Sie auf [ok] werden die Daten Ihrer aktuellen Listenansicht exportiert. Wenn Sie auf [Abbrechen] klicken, können Sie Ihre Exportkriterien neu bestimmen.',
				LBL_SELECT_COLUMN: 'Ungültige Spalte.\nBitte wählen Sie eine Spalte.',
				LBL_NOT_ACCESSIBLE : 'nicht erreichbar',
				LBL_FILENAME_LENGTH_EXCEED_ERR: 'Der Dateiname darf nicht mehr als 255 Zeichen haben.',
				LBL_DONT_HAVE_EMAIL_PERMISSION : "Sie haben keine Berechtigung für das E-Mail Feld und können somit die E-Mail Adresse nicht wählen.",
				LBL_NO_FEEDS_SELECTED: 'keine Feeds ausgewählt',
				LBL_SELECT_PICKLIST:'Bitte wenigstens einen Eintrag auswählen',
				LBL_CANT_REMOVE:'Sie können nicht alle Werte entfernen.'
                       };
	//crm-now: added for messages
	//added for PDF Configurator
	var pdfconfig_arr = {
				ITEM_INDIVIDUAL_REQUIRED_QUOTES:'Zu den Angebotsangaben müssen Sie für die Anzeige von Artikeln unter dem Tab der individuellen Mwst. mindestens einen Eintrag auswählen.',
				ITEM_GROUP_REQUIRED_QUOTES:'Zu den Angebotsangaben müssen Sie für die Anzeige von Artikeln unter dem Tab der Gruppen Mwst. mindestens einen Eintrag auswählen.',
				ITEM_INDIVIDUAL_REQUIRED_PO:'Zu den Angaben unter Einkaufsbestellungen müssen Sie für die Anzeige von Artikeln unter dem Tab der individuellen Mwst. mindestens einen Eintrag auswählen.',
				ITEM_GROUP_REQUIRED_PO:'Zu den Angaben unter Einkaufsbestellungen müssen Sie für die Anzeige von Artikeln unter dem Tab der Gruppen Mwst. mindestens einen Eintrag auswählen.',
				ITEM_INDIVIDUAL_REQUIRED_SO:'Zu den Angaben unter Verkaufsbestellungen müssen Sie für die Anzeige von Artikeln unter dem Tab der individuellen Mwst. mindestens einen Eintrag auswählen.',
				ITEM_GROUP_REQUIRED_SO:'Zu den Angaben unter Verkaufsbestellungen müssen Sie für die Anzeige von Artikeln unter dem Tab der Gruppen Mwst. mindestens einen Eintrag auswählen.',
				ITEM_INDIVIDUAL_REQUIRED_INV:'Zu den Rechnungsangaben müssen Sie für die Anzeige von Artikeln unter dem Tab der individuellen Mwst. mindestens einen Eintrag auswählen.',
				ITEM_GROUP_REQUIRED_INV:'Zu den Rechnungsangaben müssen Sie für die Anzeige von Artikeln unter dem Tab der Gruppen Mwst. mindestens einen Eintrag auswählen.',
				TAB_GENERAL:'Allgemein',
				TAB_GROUP:'Gruppen Mwst.',
				TAB_INDIVIDUAL:'Individuelle Mwst.'
			};
